services:
  backend:
    image: backend
    container_name: VoxVerse-backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - uploads_data:/app/uploads
      - temp_data:/app/temp
      - output_data:/app/output
    environment:
      DATABASE_URL: sqlite:///./data/app.db
      ALLOWED_ORIGINS: "http://localhost:3000"

  frontend:
    image: frontend
    container_name: VoxVerse-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

volumes:
  sqlite_data:
  uploads_data:
  temp_data:
  output_data: